-- Replace the externally backed hierarchy with local Supabase entities.
-- Safe for the existing invoice/time-tracking schema.

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (length(trim(title)) > 0),
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS boards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    title TEXT NOT NULL CHECK (length(trim(title)) > 0),
    description TEXT,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT NOT NULL REFERENCES boards(id),
    title TEXT NOT NULL CHECK (length(trim(title)) > 0),
    description TEXT,
    status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'in_progress', 'done')),
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    manually_archived BOOLEAN NOT NULL DEFAULT FALSE,
    billing_archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_boards_workspace_id ON boards(workspace_id);
CREATE INDEX IF NOT EXISTS idx_cards_board_id ON cards(board_id);
CREATE INDEX IF NOT EXISTS idx_cards_status ON cards(status);
CREATE INDEX IF NOT EXISTS idx_cards_active ON cards(board_id) WHERE NOT manually_archived AND NOT billing_archived;

DROP TRIGGER IF EXISTS update_workspaces_updated_at ON workspaces;
CREATE TRIGGER update_workspaces_updated_at BEFORE UPDATE ON workspaces
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_boards_updated_at ON boards;
CREATE TRIGGER update_boards_updated_at BEFORE UPDATE ON boards
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_cards_updated_at ON cards;
CREATE TRIGGER update_cards_updated_at BEFORE UPDATE ON cards
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE boards ENABLE ROW LEVEL SECURITY;
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all operations on workspaces" ON workspaces;
CREATE POLICY "Allow all operations on workspaces" ON workspaces FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow all operations on boards" ON boards;
CREATE POLICY "Allow all operations on boards" ON boards FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow all operations on cards" ON cards;
CREATE POLICY "Allow all operations on cards" ON cards FOR ALL USING (true) WITH CHECK (true);

-- Keep generated card IDs away from legacy IDs still present in snapshots/time entries.
SELECT setval(
    pg_get_serial_sequence('cards', 'id'),
    GREATEST(
        COALESCE((SELECT MAX(card_id)::BIGINT FROM invoice_cards), 0),
        COALESCE((SELECT MAX(card_id)::BIGINT FROM time_entries), 0),
        COALESCE((SELECT MAX(id) FROM cards), 0),
        1
    ),
    true
);

DROP VIEW IF EXISTS invoice_summary;
DROP VIEW IF EXISTS time_tracking_summary;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'invoices' AND column_name = 'space_id') THEN
        ALTER TABLE invoices RENAME COLUMN space_id TO workspace_id;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'invoices' AND column_name = 'space_title') THEN
        ALTER TABLE invoices RENAME COLUMN space_title TO workspace_title;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'invoice_cards' AND column_name = 'kaiten_time_spent')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'invoice_cards' AND column_name = 'legacy_time_spent') THEN
        ALTER TABLE invoice_cards RENAME COLUMN kaiten_time_spent TO legacy_time_spent;
    ELSIF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'invoice_cards' AND column_name = 'kaiten_time_spent') THEN
        UPDATE invoice_cards SET legacy_time_spent = COALESCE(legacy_time_spent, kaiten_time_spent, 0);
        ALTER TABLE invoice_cards DROP COLUMN kaiten_time_spent;
    END IF;
END $$;

ALTER TABLE invoices ALTER COLUMN workspace_id TYPE BIGINT;
ALTER TABLE invoices ALTER COLUMN board_id TYPE BIGINT;
ALTER TABLE invoice_cards ALTER COLUMN card_id TYPE BIGINT;
ALTER TABLE time_entries ALTER COLUMN card_id TYPE BIGINT;

CREATE OR REPLACE VIEW time_tracking_summary AS
SELECT
    card_id,
    COUNT(*) AS entries_count,
    SUM(hours) AS total_hours,
    SUM(minutes) AS total_minutes,
    SUM(hours * 60 + minutes) AS total_minutes_all,
    MAX(date) AS last_entry_date
FROM time_entries
GROUP BY card_id;

CREATE OR REPLACE VIEW invoice_summary AS
SELECT i.id, i.workspace_id, i.workspace_title, i.board_id, i.board_title,
       i.status, i.notes, i.created_at, i.updated_at,
       COUNT(ic.id) AS total_cards, COALESCE(SUM(ic.time_spent), 0) AS total_time_spent
FROM invoices i LEFT JOIN invoice_cards ic ON i.id = ic.invoice_id
GROUP BY i.id, i.workspace_id, i.workspace_title, i.board_id, i.board_title,
         i.status, i.notes, i.created_at, i.updated_at;

GRANT SELECT ON time_tracking_summary, invoice_summary TO anon, authenticated;

CREATE OR REPLACE FUNCTION set_invoice_status(target_invoice_id UUID, new_status TEXT)
RETURNS SETOF invoices
LANGUAGE plpgsql
AS $$
BEGIN
    IF new_status NOT IN ('draft', 'sent', 'paid') THEN
        RAISE EXCEPTION 'Invalid invoice status: %', new_status;
    END IF;

    UPDATE invoices SET status = new_status WHERE id = target_invoice_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Invoice not found'; END IF;

    UPDATE cards c
       SET billing_archived = EXISTS (
           SELECT 1 FROM invoice_cards ic
           JOIN invoices i ON i.id = ic.invoice_id
           WHERE ic.card_id = c.id AND i.status = 'paid'
       )
     WHERE c.id IN (SELECT card_id FROM invoice_cards WHERE invoice_id = target_invoice_id);

    RETURN QUERY SELECT * FROM invoices WHERE id = target_invoice_id;
END;
$$;

GRANT EXECUTE ON FUNCTION set_invoice_status(UUID, TEXT) TO anon, authenticated;

CREATE OR REPLACE FUNCTION delete_invoice(target_invoice_id UUID)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE affected_card_ids BIGINT[];
BEGIN
    SELECT ARRAY_AGG(card_id) INTO affected_card_ids FROM invoice_cards WHERE invoice_id = target_invoice_id;
    DELETE FROM invoices WHERE id = target_invoice_id;
    UPDATE cards c SET billing_archived = EXISTS (
        SELECT 1 FROM invoice_cards ic JOIN invoices i ON i.id = ic.invoice_id
        WHERE ic.card_id = c.id AND i.status = 'paid'
    ) WHERE c.id = ANY(COALESCE(affected_card_ids, ARRAY[]::BIGINT[]));
END;
$$;

GRANT EXECUTE ON FUNCTION delete_invoice(UUID) TO anon, authenticated;
