-- Complete schema for a new installation.
CREATE OR REPLACE FUNCTION update_updated_at_column() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

-- Single row. Hourly rate resolves invoice override -> workspace override -> default_hourly_rate.
CREATE TABLE app_settings (
    id BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id),
    default_hourly_rate NUMERIC(12,2) NOT NULL DEFAULT 1000 CHECK (default_hourly_rate >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
INSERT INTO app_settings DEFAULT VALUES;
CREATE TABLE workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (length(trim(title)) > 0),
    hourly_rate NUMERIC(12,2) CHECK (hourly_rate >= 0), -- NULL = inherit the default
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE boards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces(id),
    title TEXT NOT NULL CHECK (length(trim(title)) > 0), description TEXT,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT NOT NULL REFERENCES boards(id),
    title TEXT NOT NULL CHECK (length(trim(title)) > 0), description TEXT,
    status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'in_progress', 'done')),
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    manually_archived BOOLEAN NOT NULL DEFAULT FALSE, billing_archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE invoices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id BIGINT NOT NULL, workspace_title TEXT,
    board_id BIGINT NOT NULL, board_title TEXT,
    total_time_spent INTEGER NOT NULL DEFAULT 0, total_cards INTEGER NOT NULL DEFAULT 0,
    hourly_rate NUMERIC(12,2) NOT NULL CHECK (hourly_rate >= 0),
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'paid')),
    notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE invoice_cards (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), invoice_id UUID NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    card_id BIGINT NOT NULL CONSTRAINT invoice_cards_card_id_key UNIQUE, card_title TEXT NOT NULL, card_description TEXT,
    time_spent INTEGER NOT NULL DEFAULT 0, legacy_time_spent INTEGER NOT NULL DEFAULT 0,
    tracked_time_spent INTEGER NOT NULL DEFAULT 0, tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ, created_at_record TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE time_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), card_id BIGINT NOT NULL,
    hours INTEGER NOT NULL DEFAULT 0 CHECK (hours BETWEEN 0 AND 23),
    minutes INTEGER NOT NULL DEFAULT 0 CHECK (minutes BETWEEN 0 AND 59),
    description TEXT, date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT valid_time_entry CHECK (hours > 0 OR minutes > 0)
);

CREATE INDEX idx_boards_workspace_id ON boards(workspace_id);
CREATE INDEX idx_cards_board_id ON cards(board_id);
CREATE INDEX idx_cards_status ON cards(status);
CREATE INDEX idx_cards_active ON cards(board_id) WHERE NOT manually_archived AND NOT billing_archived;
CREATE INDEX idx_invoices_workspace_id ON invoices(workspace_id);
CREATE INDEX idx_invoices_board_id ON invoices(board_id);
CREATE INDEX idx_invoices_status ON invoices(status);
CREATE INDEX idx_invoice_cards_invoice_id ON invoice_cards(invoice_id);
CREATE INDEX idx_time_entries_card_id ON time_entries(card_id);
CREATE INDEX idx_time_entries_date ON time_entries(date);

CREATE TRIGGER update_app_settings_updated_at BEFORE UPDATE ON app_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_workspaces_updated_at BEFORE UPDATE ON workspaces FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_boards_updated_at BEFORE UPDATE ON boards FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_cards_updated_at BEFORE UPDATE ON cards FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_invoices_updated_at BEFORE UPDATE ON invoices FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_time_entries_updated_at BEFORE UPDATE ON time_entries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE VIEW time_tracking_summary AS
SELECT card_id, COUNT(*) AS entries_count, SUM(hours) AS total_hours, SUM(minutes) AS total_minutes,
       SUM(hours * 60 + minutes) AS total_minutes_all, MAX(date) AS last_entry_date
FROM time_entries GROUP BY card_id;
CREATE VIEW invoice_summary AS
SELECT i.id, i.workspace_id, i.workspace_title, i.board_id, i.board_title, i.status, i.notes,
       i.created_at, i.updated_at, COUNT(ic.id) AS total_cards,
       COALESCE(SUM(ic.time_spent), 0) AS total_time_spent
FROM invoices i LEFT JOIN invoice_cards ic ON i.id = ic.invoice_id
GROUP BY i.id, i.workspace_id, i.workspace_title, i.board_id, i.board_title,
         i.status, i.notes, i.created_at, i.updated_at;

GRANT SELECT ON time_tracking_summary, invoice_summary TO anon, authenticated;

CREATE OR REPLACE FUNCTION set_invoice_status(target_invoice_id UUID, new_status TEXT)
RETURNS SETOF invoices LANGUAGE plpgsql AS $$
BEGIN
    IF new_status NOT IN ('draft', 'sent', 'paid') THEN RAISE EXCEPTION 'Invalid invoice status: %', new_status; END IF;
    UPDATE invoices SET status = new_status WHERE id = target_invoice_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Invoice not found'; END IF;
    UPDATE cards c SET billing_archived = EXISTS (
        SELECT 1 FROM invoice_cards ic JOIN invoices i ON i.id = ic.invoice_id
        WHERE ic.card_id = c.id AND i.status = 'paid'
    ) WHERE c.id IN (SELECT card_id FROM invoice_cards WHERE invoice_id = target_invoice_id);
    RETURN QUERY SELECT * FROM invoices WHERE id = target_invoice_id;
END;
$$;

CREATE OR REPLACE FUNCTION effective_hourly_rate(target_workspace_id BIGINT)
RETURNS NUMERIC LANGUAGE sql STABLE AS $$
    SELECT COALESCE(w.hourly_rate, s.default_hourly_rate)
    FROM app_settings s LEFT JOIN workspaces w ON w.id = target_workspace_id
$$;

CREATE OR REPLACE FUNCTION create_invoice_with_cards(target_board_id BIGINT, card_ids BIGINT[], invoice_notes TEXT DEFAULT NULL,
                                                     invoice_hourly_rate NUMERIC DEFAULT NULL)
RETURNS SETOF invoices LANGUAGE plpgsql AS $$
DECLARE
    target_board boards%ROWTYPE; target_workspace workspaces%ROWTYPE;
    unique_card_ids BIGINT[]; valid_count INTEGER; new_invoice_id UUID;
BEGIN
    unique_card_ids := ARRAY(SELECT DISTINCT unnest(COALESCE(card_ids, ARRAY[]::BIGINT[])));
    IF cardinality(unique_card_ids) = 0 THEN RAISE EXCEPTION 'No cards selected'; END IF;
    SELECT * INTO target_board FROM boards WHERE id = target_board_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Board not found'; END IF;
    SELECT * INTO target_workspace FROM workspaces WHERE id = target_board.workspace_id;
    -- Lock the cards so their status/archive state cannot change while the invoice is created.
    PERFORM 1 FROM cards WHERE id = ANY(unique_card_ids) ORDER BY id FOR UPDATE;
    SELECT COUNT(*) INTO valid_count FROM cards
    WHERE id = ANY(unique_card_ids) AND board_id = target_board_id AND status = 'done'
      AND NOT manually_archived AND NOT billing_archived;
    IF valid_count <> cardinality(unique_card_ids) THEN RAISE EXCEPTION 'Some cards cannot be invoiced'; END IF;
    -- Friendly error; invoice_cards_card_id_key is the actual guarantee.
    IF EXISTS (SELECT 1 FROM invoice_cards WHERE card_id = ANY(unique_card_ids)) THEN
        RAISE EXCEPTION 'Some cards are already included in another invoice' USING ERRCODE = 'unique_violation';
    END IF;
    INSERT INTO invoices (workspace_id, workspace_title, board_id, board_title, status, notes, hourly_rate)
    VALUES (target_workspace.id, target_workspace.title, target_board.id, target_board.title, 'draft', invoice_notes,
            COALESCE(invoice_hourly_rate, effective_hourly_rate(target_workspace.id)))
    RETURNING id INTO new_invoice_id;
    INSERT INTO invoice_cards (invoice_id, card_id, card_title, card_description,
                               time_spent, legacy_time_spent, tracked_time_spent, tags, created_at)
    SELECT new_invoice_id, c.id, c.title, c.description, COALESCE(s.total_minutes_all, 0)::INTEGER, 0,
           COALESCE(s.total_minutes_all, 0)::INTEGER, c.tags, c.created_at
    FROM cards c LEFT JOIN time_tracking_summary s ON s.card_id = c.id
    WHERE c.id = ANY(unique_card_ids);
    UPDATE invoices i SET total_cards = t.card_count, total_time_spent = t.total_time
    FROM (SELECT COUNT(*) AS card_count, COALESCE(SUM(time_spent), 0) AS total_time
          FROM invoice_cards WHERE invoice_id = new_invoice_id) t
    WHERE i.id = new_invoice_id;
    RETURN QUERY SELECT * FROM invoices WHERE id = new_invoice_id;
END;
$$;

CREATE OR REPLACE FUNCTION delete_invoice(target_invoice_id UUID)
RETURNS VOID LANGUAGE plpgsql AS $$
DECLARE affected_card_ids BIGINT[];
BEGIN
    SELECT ARRAY_AGG(card_id) INTO affected_card_ids FROM invoice_cards WHERE invoice_id = target_invoice_id;
    DELETE FROM invoices WHERE id = target_invoice_id;
    UPDATE cards c SET billing_archived = EXISTS (
        SELECT 1 FROM invoice_cards ic JOIN invoices i ON i.id = ic.invoice_id
        WHERE ic.card_id = c.id AND i.status = 'paid'
    ) WHERE c.id = ANY(COALESCE(affected_card_ids, ARRAY[]::BIGINT[]));
END;
$$;

ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY; ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY; ALTER TABLE boards ENABLE ROW LEVEL SECURITY;
ALTER TABLE cards ENABLE ROW LEVEL SECURITY; ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_cards ENABLE ROW LEVEL SECURITY; ALTER TABLE time_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations on app_settings" ON app_settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on workspaces" ON workspaces FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on boards" ON boards FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on cards" ON cards FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on invoices" ON invoices FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on invoice_cards" ON invoice_cards FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on time_entries" ON time_entries FOR ALL USING (true) WITH CHECK (true);
GRANT EXECUTE ON FUNCTION set_invoice_status(UUID, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION delete_invoice(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION effective_hourly_rate(BIGINT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION create_invoice_with_cards(BIGINT, BIGINT[], TEXT, NUMERIC) TO anon, authenticated;
